/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package imu_msg;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class imu implements lcm.lcm.LCMEncodable
{
    public double yaw;
    public double pitch;
    public double roll;
    public double magn_x;
    public double magn_y;
    public double magn_z;
    public double accl_x;
    public double accl_y;
    public double accl_z;
    public double gyro_x;
    public double gyro_y;
    public double gyro_z;
 
    public imu()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x997ae2b0fc4d06ddL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(imu_msg.imu.class))
            return 0L;
 
        classes.add(imu_msg.imu.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeDouble(this.yaw); 
 
        outs.writeDouble(this.pitch); 
 
        outs.writeDouble(this.roll); 
 
        outs.writeDouble(this.magn_x); 
 
        outs.writeDouble(this.magn_y); 
 
        outs.writeDouble(this.magn_z); 
 
        outs.writeDouble(this.accl_x); 
 
        outs.writeDouble(this.accl_y); 
 
        outs.writeDouble(this.accl_z); 
 
        outs.writeDouble(this.gyro_x); 
 
        outs.writeDouble(this.gyro_y); 
 
        outs.writeDouble(this.gyro_z); 
 
    }
 
    public imu(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public imu(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static imu_msg.imu _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        imu_msg.imu o = new imu_msg.imu();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.yaw = ins.readDouble();
 
        this.pitch = ins.readDouble();
 
        this.roll = ins.readDouble();
 
        this.magn_x = ins.readDouble();
 
        this.magn_y = ins.readDouble();
 
        this.magn_z = ins.readDouble();
 
        this.accl_x = ins.readDouble();
 
        this.accl_y = ins.readDouble();
 
        this.accl_z = ins.readDouble();
 
        this.gyro_x = ins.readDouble();
 
        this.gyro_y = ins.readDouble();
 
        this.gyro_z = ins.readDouble();
 
    }
 
    public imu_msg.imu copy()
    {
        imu_msg.imu outobj = new imu_msg.imu();
        outobj.yaw = this.yaw;
 
        outobj.pitch = this.pitch;
 
        outobj.roll = this.roll;
 
        outobj.magn_x = this.magn_x;
 
        outobj.magn_y = this.magn_y;
 
        outobj.magn_z = this.magn_z;
 
        outobj.accl_x = this.accl_x;
 
        outobj.accl_y = this.accl_y;
 
        outobj.accl_z = this.accl_z;
 
        outobj.gyro_x = this.gyro_x;
 
        outobj.gyro_y = this.gyro_y;
 
        outobj.gyro_z = this.gyro_z;
 
        return outobj;
    }
 
}

